spring:
  datasource:
    url: jdbc:mysql://localhost:3306/salesdb
    username: kasai
    password: 9001184
    driver-class-name: com.mysql.cj.jdbc.Driver
  
logging:
  level:
    com:
      mksai:
        springboot: DEBUG
 